[workspace]
members = [
    "amp_cli",
    "amp_gui",
    "amp_lib"
]

[workspace.package]
version = "0.1.0"
authors = ["PikminGuts92"]
edition = "2021"

[workspace.dependencies]
grim = { path = "../grim/core/grim", features = [ "audio", "midi" ] }