[package]
name = "amp_lib"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
grim = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.104"